school:
 upass: "Dear Parents, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, for any query contact +8801685012605. GGIS"
 epass: "Dear Parents, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, for any query contact +8801685012605. GGIS"
 tpass: "Dear Employee, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, for any query contact +8801685012605. GGIS"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. GGIS"
 feepaid: "Fees received BDT #AMOUNT# for #UNAME#(#UID#) as on #PAIDDATE# by TBL. TranID-#TRANID# TranRef-#TRANREF#, GGIS"
